# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'des2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#importing gtts module to convert text into Speech.pip install gtts

from gtts import gTTS
#importing random libr to store output file with diffrent no.
import random

class Ui_MainWindow(object):
        # Function for alert message dialog
    def alertBox(self,title,message):

            Window=QtWidgets.QMessageBox()
            Window.setWindowTitle(title)
            Window.setText(message)
            Window.setStandardButtons(QtWidgets.QMessageBox.Ok)
            Window.exec_()
        # Function that converting text into speech.
    def Text2Speech(self):
        # Converting text to string and Storing in input_text variable

            input_text=str(self.Label_textArea.toPlainText())
        # check if user enter nothing.
            if len(input_text)==0:

                    self.alertBox("Empty","Please Enter OR Paste Your text.")
            else:

                    # audio language English.
                    language="en"
                    number=random.randrange(100,999)
                    getSixChar=input_text[0:6]
                    # Generating output file.
                    filename="output"+str(number)+"-"+getSixChar+".mp3"
                    #calling gTTS to convert text into Speech.
                    file=gTTS(text=input_text,lang=language,slow=False)
                    #saving File.
                    file.save(filename)
                    #checking error in File.
                    if file !="" or file!=None:
                            self.alertBox("Success!","Your audio file genrated Successfully.check your output Folder.")
                    else:
                            self.alertBox("Error!","Something Went Wrong!")
                
                  
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(602, 528)
        MainWindow.setStyleSheet("background-image: url(:/newPrefix/bground.png);\n"
"background-repeat:no-repeat;\n"
"background-attachment:fixed;\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(190, 20, 191, 51))
        self.title_label.setStyleSheet("font-family:calibri;\n"
"font-weight:900;\n"
"font-size:28px;\n"
"background-image:url(none);\n"
"color:black;")
        self.title_label.setObjectName("title_label")
        self.Label_text = QtWidgets.QLabel(self.centralwidget)
        self.Label_text.setGeometry(QtCore.QRect(80, 100, 221, 41))
        self.Label_text.setStyleSheet("font-family:calibri;\n"
"font-weight:900;\n"
"font-size:20px;\n"
"background-image:url(none);\n"
"color:black;")
        self.Label_text.setObjectName("Label_text")
        self.Label_textArea = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Label_textArea.setGeometry(QtCore.QRect(80, 150, 431, 211))
        self.Label_textArea.setStyleSheet("font-family:calibri;\n"
"font-size:14px;\n"
"font-weight:bold;\n"
"color:black;\n"
"padding:8px;\n"
"border:2px solid skyblue;\n"
"border-radius:10px ;\n"
"")
        self.Label_textArea.setObjectName("Label_textArea")
        self.Convert_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Convert_Button.setGeometry(QtCore.QRect(80, 400, 431, 41))
        self.Convert_Button.setStyleSheet("font-family:calibri;\n"
"font-weight:bold;\n"
"font-size:20px;\n"
"border-radius:8px;\n"
"color:black;\n"
"background-image:url(none);\n"
"background-color:rgb(79, 134, 169);")
        self.Convert_Button.setObjectName("Convert_Button")
        MainWindow.setCentralWidget(self.centralwidget)
 # Connecting Text2Speech function with Convert_button
        self.Convert_Button.clicked.connect(self.Text2Speech)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Text to Speech Translator"))
        self.title_label.setText(_translate("MainWindow", "  Text to Speech"))
        self.Label_text.setText(_translate("MainWindow", " Write or Paste Your text:"))
        self.Convert_Button.setText(_translate("MainWindow", "Convert to audio"))
import sourceQt


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
